### ISSUE TITLE
Single-warning titles render without space before 'Warning'

### ISSUE THREAD

**Issue by lexie-em** [Alamantus/RedFlag#1]
**What I did:**

Created a link with a single warning ("Body Horror", in case it matters), and visited the link.

**What I expected to see:**

The warning page titled "Body Horror Warning".

**What I actually saw:**

The warning page titled "Body HorrorWarning" (no space between "Horror" and "Warning").

**Notes:**

- With multiple warnings selected, the behavior appears correct, e.g. "Body Horror and Body Shaming Warning".
- Sorry I couldn't submit a PR with a fix! I'm not familiar with the framework you're using to render the warning page, and it wasn't clear to me in the code how the title is being constructed.
- I really like what you're doing here! I was going to buy you a coffee, but it looks like your Ko-Fi account is paused due to inactivity? If you want to reactivate it, let me know, and I'll do the thing. Thanks!

**Comment by Alamantus** [comment]
Thanks for letting me know about this! I've fixed this issue and it should now be displaying correctly.

Also, I re-activated my Ko-Fi account! I didn't realize it paused after a time.
