### ISSUE TITLE
Readme and About page use "grizzly" instead of "grisly"

### ISSUE THREAD

**Issue by SpencerDub** [Alamantus/RedFlag#2]
This is a very, very, very minor thing that does not change the functionality at all!

But the About page and the Readme both use the word "grizzly" to describe something gruesome and horrific:

> Dog rescues and many other sources shared this article, which featured and previewed the grizzly images.

But [grizzly](https://www.thefreedictionary.com/grizzly) means "grayish or flecked with gray". It is a separate word from "[grisly](https://www.thefreedictionary.com/grisly)", which means "gruesome, grim, or horrific".

**Comment by Alamantus** [comment]
Whoops, you are totally right! I'm not sure why I got that wrong, because I do know the difference between those words... 😅

Thanks so much for catching that! I've updated it now.
