### ISSUE TITLE
Doesn’t work on iPhone SE 2020

### ISSUE THREAD

**Issue by Patabugen** [Alamantus/RedFlag#3]
The warning page isn’t responsive and the contrast between the colours, especially at that size, makes it unusable.

This is on an iPhone SE 2020 running iOS 14.6. It’s probably a similar experience for all iPhone users.

**Comment by Patabugen** [comment]
![Uploading 5EA5AEA8-3C1C-437D-83C8-A36FD9EA72EF.png…]()

**Comment by Alamantus** [comment]
Thanks for creating this ticket! I knew about the buttons not displaying correctly, but I didn't realize just how bad it actually was. This issue with text in buttons not wrapping has plagued me for ages, but I finally figured out how to fix it thanks to this little push.

I've uploaded the fix, and it appears to be displaying correctly on small screens now!
